name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker image
        run: |
          docker build -t devops-lab-service -f docker/Dockerfile .

      - name: Run container
        run: |
          docker run -d -p 8000:8000 --name test-app devops-lab-service
          sleep 5
          curl --fail http://localhost:8000/ || exit 1
          docker stop test-app
          docker rm test-app
